[build]
  publish = "dist"
  command = "npm ci && npm run build"
  functions = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "22"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NPM_CONFIG_PRODUCTION = "false"
  CI = "true"
  # Avoid timezone issues
  TZ = "UTC"
  # Ensure TypeScript compilation
  NODE_ENV = "production"

# Build optimizations
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers - using _headers file instead for better control
# but keeping some basic ones here as fallback

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Edge processing for faster builds
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "production" }

[context.branch-deploy]
  environment = { NODE_ENV = "production" }